[tool.isort]
profile = "black"
multi_line_output = 3


[tool.flake8]
max-line-length = 88
extend-ignore = ["D203", "E203", "E251", "E266", "E302", "E305", "E401", "E402", "E501", "F401", "F403", "W503"]

[tool.mypy]
namespace_packages = true